import {
  BarChart3,
  DatabaseZap,
  FileText,
  FolderTree,
  Image,
  LayoutDashboard,
  LockKeyhole,
  Newspaper,
  SearchCheck,
  Settings,
  ShieldCheck,
  Users,
} from "lucide-react";

export const adminModules = [
  { key: "dashboard", label: "数据概览", href: "/admin", icon: LayoutDashboard, permission: "dashboard.view" },
  { key: "products", label: "产品管理", href: "/admin/products", icon: FileText, permission: "products.view" },
  { key: "categories", label: "产品分类", href: "/admin/categories", icon: FolderTree, permission: "categories.manage" },
  { key: "news", label: "新闻管理", href: "/admin/news", icon: Newspaper, permission: "news.manage" },
  { key: "leads", label: "客户表单", href: "/admin/leads", icon: Users, permission: "leads.manage" },
  { key: "analytics", label: "访问分析", href: "/admin/analytics", icon: BarChart3, permission: "analytics.view" },
  { key: "seo", label: "SEO数据", href: "/admin/seo", icon: SearchCheck, permission: "seo.manage" },
  { key: "media", label: "媒体库", href: "/admin/media", icon: Image, permission: "media.manage" },
  { key: "users", label: "用户与权限", href: "/admin/users", icon: ShieldCheck, permission: "users.manage" },
  { key: "audit-logs", label: "操作日志", href: "/admin/audit-logs", icon: LockKeyhole, permission: "audit.view" },
  { key: "settings", label: "系统设置", href: "/admin/settings", icon: Settings, permission: "settings.manage" },
  { key: "sync", label: "数据同步", href: "/admin/sync", icon: DatabaseZap, permission: "sync.manage" },
];

export const moduleContent = {
  products: {
    title: "产品管理",
    description: "查看和维护当前前台发布的产品内容、分类归属、前台链接和SEO状态。",
    apiModule: "products",
    columns: ["产品名称", "型号", "Slug", "状态", "前台链接", "分类"],
    actions: ["新增产品", "批量发布", "批量下架", "导入", "导出"],
  },
  categories: {
    title: "产品分类",
    description: "查看当前前台导航展示的产品分类、层级、排序和启用状态。",
    apiModule: "categories",
    columns: ["分类名称", "英文名称", "Slug", "层级", "启用", "排序"],
    actions: ["新增分类", "批量启用", "批量停用", "导入", "导出"],
  },
  news: {
    title: "新闻管理",
    description: "查看当前新闻中心发布的文章、分类、发布时间和前台状态。",
    apiModule: "news",
    columns: ["标题", "分类", "作者", "状态", "发布时间", "浏览量"],
    actions: ["新增新闻", "批量发布", "批量下架", "导入", "导出"],
  },
  leads: {
    title: "客户表单",
    description: "查看询盘、分配负责人、分类跟进、添加备注和导出客户数据。",
    apiModule: "leads",
    columns: ["编号", "姓名", "公司", "邮箱", "国家", "状态", "提交时间"],
    actions: ["批量分配", "批量分类", "标记垃圾", "导出"],
  },
  analytics: {
    title: "访问分析",
    description: "查看当前网站内容规模和访问数据源状态。",
    apiModule: "analytics",
    columns: ["范围", "产品数量", "产品值", "新闻数量", "新闻值", "备注"],
    actions: ["同步数据", "导出报表"],
  },
  seo: {
    title: "SEO数据",
    description: "查看站内SEO基础检查、页面状态和需要处理的问题。",
    apiModule: "seo",
    columns: ["问题类型", "严重程度", "页面", "状态", "建议", "负责人"],
    actions: ["扫描站点", "同步GSC", "导出问题"],
  },
  media: {
    title: "媒体库",
    description: "查看当前网站使用的产品图片、工厂图片、行业图片和来源信息。",
    apiModule: "media",
    columns: ["文件名", "类型", "路径", "来源", "分类", "使用位置"],
    actions: ["上传文件", "批量删除", "导出清单"],
  },
  users: {
    title: "用户与权限",
    description: "管理后台用户、角色、权限、登录状态和会话。",
    apiModule: "users",
    columns: ["姓名", "邮箱", "角色", "状态", "最后登录", "创建时间"],
    actions: ["新增用户", "分配角色", "停用用户"],
  },
  "audit-logs": {
    title: "操作日志",
    description: "记录登录、内容发布、导出、同步和系统配置变更。",
    apiModule: "audit-logs",
    columns: ["用户", "模块", "操作", "对象", "结果", "时间"],
    actions: ["导出日志"],
  },
  settings: {
    title: "系统设置",
    description: "查看当前网站名称、域名、时区和询盘接收邮箱等运行配置。",
    apiModule: "settings",
    columns: ["配置项", "值", "敏感", "更新时间"],
    actions: ["保存设置", "测试邮件", "测试存储"],
  },
  sync: {
    title: "数据同步",
    description: "查看网站内容、客户表单和外部SEO数据源的连接状态。",
    apiModule: "sync",
    columns: ["数据源", "配置状态", "连接状态", "同步状态", "最后同步", "最近错误"],
    actions: ["手动同步", "查看日志"],
  },
} as const;

export type AdminModuleKey = keyof typeof moduleContent;
